// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATVZesvpi1PeWY8Qf8pvuHMFrlcp_Zjiw',
    appId: '1:374488131757:web:cc24a7e7f093fab25c3e24',
    messagingSenderId: '374488131757',
    projectId: 'portfolio-3261f',
    authDomain: 'portfolio-3261f.firebaseapp.com',
    storageBucket: 'portfolio-3261f.firebasestorage.app',
    measurementId: 'G-CFBPP2SLM9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDj_ZEhYHePFRuTw6whlbxb3frt-f5Q2Yk',
    appId: '1:374488131757:android:ade8512e3af302f95c3e24',
    messagingSenderId: '374488131757',
    projectId: 'portfolio-3261f',
    storageBucket: 'portfolio-3261f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnWesZXNag03MDXSWkd8TatyzB51pPKB4',
    appId: '1:374488131757:ios:1d86041f0bc9b1bc5c3e24',
    messagingSenderId: '374488131757',
    projectId: 'portfolio-3261f',
    storageBucket: 'portfolio-3261f.firebasestorage.app',
    iosBundleId: 'com.bio.portfolio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnWesZXNag03MDXSWkd8TatyzB51pPKB4',
    appId: '1:374488131757:ios:1d86041f0bc9b1bc5c3e24',
    messagingSenderId: '374488131757',
    projectId: 'portfolio-3261f',
    storageBucket: 'portfolio-3261f.firebasestorage.app',
    iosBundleId: 'com.bio.portfolio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyATVZesvpi1PeWY8Qf8pvuHMFrlcp_Zjiw',
    appId: '1:374488131757:web:fcc857c242dc99a75c3e24',
    messagingSenderId: '374488131757',
    projectId: 'portfolio-3261f',
    authDomain: 'portfolio-3261f.firebaseapp.com',
    storageBucket: 'portfolio-3261f.firebasestorage.app',
    measurementId: 'G-6B5S9CNLGG',
  );
}
